# Generated by Django 3.1.2 on 2020-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='username1',
            field=models.CharField(default='', max_length=20),
        ),
    ]
