# Generated by Django 3.1.2 on 2020-11-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account2', '0002_user_info_username1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='Total_Question_faced',
            field=models.IntegerField(default=0),
        ),
    ]
