# Generated by Django 3.1.2 on 2020-11-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='Class',
            field=models.IntegerField(default=5),
        ),
    ]
