# Generated by Django 3.1.2 on 2020-11-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_que_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que',
            name='Class',
            field=models.IntegerField(),
        ),
    ]
