# Generated by Django 3.1.2 on 2020-11-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201102_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct_ans',
            field=models.BooleanField(default=False),
        ),
    ]
