# Generated by Django 3.1.2 on 2020-11-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account2', '0002_user_info_username1'),
        ('app1', '0004_choice_correct_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account2.user_info'),
        ),
    ]
