# Generated by Django 3.1.2 on 2020-11-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_que_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='que',
            name='user',
        ),
        migrations.AddField(
            model_name='que',
            name='biology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='que',
            name='chemistry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='que',
            name='maths',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='que',
            name='physics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='que',
            name='science',
            field=models.BooleanField(default=False),
        ),
    ]
