# Generated by Django 3.1.2 on 2020-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20201122_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
