# Generated by Django 3.1.2 on 2020-11-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('question_text', models.CharField(max_length=200)),
                ('correct_ans', models.CharField(max_length=20)),
            ],
        ),
    ]
