# Generated by Django 3.1.2 on 2020-11-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_res',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
