# Generated by Django 3.1.2 on 2020-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account3', '0003_user_res_solved_c_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_res',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
